name: Update README

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Run script to fetch data and update README.md
        run: bun index.js
      - name: Commit changes to README.md
        uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"
          message: "Fetch data and update README"
          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          # Default: github_actor
          default_author: github_actions
